import { Category, Product } from '@/lib/types';

export const sampleCategories: Category[] = [
  {
    id: 'vitamins',
    slug: 'vitamins',
    name_en: 'Vitamins',
    name_he: 'ויטמינים',
    sort_order: 1
  },
  {
    id: 'minerals',
    slug: 'minerals',
    name_en: 'Minerals',
    name_he: 'מינרלים',
    sort_order: 2
  },
  {
    id: 'herbal',
    slug: 'herbal',
    name_en: 'Herbal',
    name_he: 'צמחי מרפא',
    sort_order: 3
  },
  {
    id: 'omega',
    slug: 'omega',
    name_en: 'Omega 3',
    name_he: 'אומגה 3',
    sort_order: 4
  },
  {
    id: 'probiotics',
    slug: 'probiotics',
    name_en: 'Probiotics',
    name_he: 'פרוביוטיקה',
    sort_order: 5
  },
  {
    id: 'protein',
    slug: 'protein',
    name_en: 'Protein',
    name_he: 'חלבון',
    sort_order: 6
  }
];

export const sampleProducts: Product[] = [
  {
    id: 'prod-1',
    slug: 'daily-multi',
    name_en: 'Daily Multi Essentials',
    name_he: 'מולטי ויטמין יומי',
    brand: 'Nordic Roots',
    description_en: 'Complete daily multivitamin with methylated B-complex.',
    description_he: 'מולטי ויטמין יומי מלא עם קומפלקס B מתילטי.',
    ingredients_en: 'Vitamin A, C, D3, E, B6, B12, Folate, Zinc.',
    ingredients_he: 'ויטמין A, C, D3, E, B6, B12, חומצה פולית, אבץ.',
    price_ils: 149,
    sale_price_ils: 129,
    stock_qty: 42,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'vitamins'
  },
  {
    id: 'prod-2',
    slug: 'vitamin-d3-k2',
    name_en: 'Vitamin D3 + K2 Balance',
    name_he: 'ויטמין D3 עם K2',
    brand: 'Sunwise',
    description_en: 'Immune and bone support with synergistic D3 + K2.',
    description_he: 'תמיכה חיסונית ועצמות עם שילוב D3 ו-K2.',
    ingredients_en: 'Vitamin D3 2000 IU, Vitamin K2 MK-7.',
    ingredients_he: 'ויטמין D3 2000 יחב״ל, ויטמין K2 MK-7.',
    price_ils: 89,
    sale_price_ils: null,
    stock_qty: 65,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1550572017-edd951aa8f7e?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'vitamins'
  },
  {
    id: 'prod-3',
    slug: 'magnesium-glycinate',
    name_en: 'Magnesium Glycinate Calm',
    name_he: 'מגנזיום גליצינאט',
    brand: 'MineralCraft',
    description_en: 'Gentle, highly absorbable magnesium for relaxation.',
    description_he: 'מגנזיום עדין ונספג היטב להרפיה.',
    ingredients_en: 'Magnesium (bisglycinate) 200mg.',
    ingredients_he: 'מגנזיום (ביסגליצינאט) 200 מ״ג.',
    price_ils: 119,
    sale_price_ils: 105,
    stock_qty: 38,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1616671276441-2f2cf1e7b1a2?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'minerals'
  },
  {
    id: 'prod-4',
    slug: 'omega-3-pure',
    name_en: 'Omega-3 Pure Strength',
    name_he: 'אומגה 3 עוצמתי',
    brand: 'BlueCurrent',
    description_en: 'Triple-tested fish oil with high EPA/DHA.',
    description_he: 'שמן דגים בבדיקות איכות עם EPA/DHA גבוהים.',
    ingredients_en: 'Fish oil concentrate, natural lemon flavor.',
    ingredients_he: 'ריכוז שמן דגים, טעם לימון טבעי.',
    price_ils: 159,
    sale_price_ils: null,
    stock_qty: 27,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'omega'
  },
  {
    id: 'prod-5',
    slug: 'probiotic-20b',
    name_en: 'Probiotic 20B CFU',
    name_he: 'פרוביוטיקה 20 מיליארד',
    brand: 'FloraLab',
    description_en: 'Daily gut support with 10 diverse strains.',
    description_he: 'תמיכה יומית במערכת העיכול עם 10 זנים שונים.',
    ingredients_en: 'Lactobacillus, Bifidobacterium blends.',
    ingredients_he: 'לקטובצילוס, ביפידובקטריום.',
    price_ils: 139,
    sale_price_ils: 119,
    stock_qty: 50,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1584362917165-526a968579e8?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'probiotics'
  },
  {
    id: 'prod-6',
    slug: 'turmeric-curcumin',
    name_en: 'Turmeric Curcumin Ultra',
    name_he: 'כורכום כורכומין',
    brand: 'HerbaPure',
    description_en: 'Inflammation support with bio-enhanced curcumin.',
    description_he: 'תמיכה אנטי-דלקתית עם כורכומין מוגבר זמינות.',
    ingredients_en: 'Curcumin, black pepper extract.',
    ingredients_he: 'כורכומין, תמצית פלפל שחור.',
    price_ils: 129,
    sale_price_ils: null,
    stock_qty: 33,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'herbal'
  },
  {
    id: 'prod-7',
    slug: 'ashwagandha-balance',
    name_en: 'Ashwagandha Balance',
    name_he: 'אשווגנדה איזון',
    brand: 'Adaptogenica',
    description_en: 'Adaptogenic support for stress and focus.',
    description_he: 'תמיכה אדפטוגנית ללחץ וריכוז.',
    ingredients_en: 'KSM-66 Ashwagandha extract.',
    ingredients_he: 'תמצית אשווגנדה KSM-66.',
    price_ils: 112,
    sale_price_ils: 98,
    stock_qty: 41,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1505250469679-203ad9ced0cb?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'herbal'
  },
  {
    id: 'prod-8',
    slug: 'collagen-peptides',
    name_en: 'Collagen Peptides',
    name_he: 'קולגן פפטידים',
    brand: 'GlowForm',
    description_en: 'Unflavored collagen for skin, hair, and joints.',
    description_he: 'קולגן ללא טעם לעור, שיער ומפרקים.',
    ingredients_en: 'Hydrolyzed collagen peptides.',
    ingredients_he: 'פפטידי קולגן הידרוליזה.',
    price_ils: 189,
    sale_price_ils: 169,
    stock_qty: 19,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1505576633757-0ac1084af824?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'protein'
  },
  {
    id: 'prod-9',
    slug: 'whey-vanilla',
    name_en: 'Whey Protein Vanilla',
    name_he: 'חלבון מי גבינה וניל',
    brand: 'PrimeFuel',
    description_en: 'Clean whey isolate with a soft vanilla finish.',
    description_he: 'חלבון מי גבינה מבודד בטעם וניל עדין.',
    ingredients_en: 'Whey protein isolate, natural vanilla.',
    ingredients_he: 'חלבון מי גבינה מבודד, וניל טבעי.',
    price_ils: 219,
    sale_price_ils: null,
    stock_qty: 14,
    same_day_eligible: false,
    image_url: 'https://images.unsplash.com/photo-1582719367198-6bfcd2a72a23?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'protein'
  },
  {
    id: 'prod-10',
    slug: 'zinc-c-immune',
    name_en: 'Zinc + C Immune Shield',
    name_he: 'אבץ + ויטמין C',
    brand: 'ClearShield',
    description_en: 'Daily immune blend with zinc and buffered vitamin C.',
    description_he: 'שילוב חיסוני יומי עם אבץ וויטמין C מאוזן.',
    ingredients_en: 'Zinc 15mg, Vitamin C 500mg.',
    ingredients_he: 'אבץ 15 מ"ג, ויטמין C 500 מ"ג.',
    price_ils: 79,
    sale_price_ils: 69,
    stock_qty: 58,
    same_day_eligible: true,
    image_url: 'https://images.unsplash.com/photo-1597931752949-98c74b5b159f?auto=format&fit=crop&w=800&q=80',
    primary_category_id: 'minerals'
  }
];
